version: 2
jobs:
  lint:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          # $NPMRC is saved in OnePassword for reference:
          # https://connctd.1password.com/vaults/nofs7a4sjhz6iyje5at6lp2i7u/allitems/zpzkgifbzfelvdasqjncutefay
          command: echo $NPMRC | base64 -d > .npmrc && yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
